baseurl = "http://gaysianthirdspace.com/"
defaultContentLanguage = "en"
disqusShortname = ""
googleAnalytics = "UA-77731767-1"
languageCode = "en-us"
paginate = 10
theme = "hugo-universal-theme"
title = "GaysianThirdSpace"
[Permalinks]
blog = "/blog/:year/:month/:day/:filename/"
[[menu.main]]
identifier = "programs-meetups"
name = "Meetups"
parent = "programs"
url = "/meetups/"
weight = 2
[[menu.main]]
identifier = "programs-overview"
name = "Overview"
parent = "programs"
url = "/programs/"
weight = 1
[[menu.main]]
identifier = "programs"
name = "Programs"
url = "#"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4
[[menu.topbar]]
name = "Tumblr"
pre = "<i class='fa fa-2x fa-tumblr'></i>"
url = "http://gaysianthirdspace.tumblr.com"
weight = 1
[[menu.topbar]]
name = "Facebook"
pre = "<i class='fa fa-2x fa-facebook'></i>"
url = "http://facebook.com/gaysianthirdspace"
weight = 2
[[menu.topbar]]
name = "Instagram"
pre = "<i class='fa fa-2x fa-instagram'></i>"
url = "http://instagram.com/gaysianthirdspace"
weight = 3
[[menu.topbar]]
name = "Email"
pre = "<i class='fa fa-2x fa-envelope'></i>"
url = "mailto:gaysianthirdspace@gmail.com"
weight = 4
[params]
about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
address = "<p><strong>Universal Ltd.</strong>\n        <br>13/25 New Avenue\n        <br>Newtown upon River\n        <br>45Y 73J\n        <br>England\n        <br>\n        <strong>Great Britain</strong>\n      </p>\n      "
author = "DevCows"
copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
date_format = "January 2, 2006"
defaultdescription = "Site template made by devcows using hugo"
defaultkeywords = ["devows", "hugo", "go"]
email = "your@email.com"
googlemapsapikey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"
latitude = "-12.043333"
logo = "img/logo.png"
longitude = "-77.028333"
style = "default"
viewmorepostlink = "/blog/"
[params.carousel]
enable = true
[params.clients]
enable = true
subtitle = ""
title = "Sibling Organizations"
[params.features]
enable = true
[params.recent_posts]
enable = false
subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
title = "From our blog"
[params.see_more]
enable = true
icon = "fa fa-file-code-o"
link_text = "Check other homepages"
link_url = "#"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
title = "Do you want to see more?"
[params.testimonials]
enable = true
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
title = "Testimonials"
[params.topbar]
enable = false
text = "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\n      <p class=\"hidden-md hidden-lg\"><a href=\"#\" data-animate-hover=\"pulse\"><i class=\"fa fa-phone\"></i></a>\n      <a href=\"#\" data-animate-hover=\"pulse\"><i class=\"fa fa-envelope\"></i></a>\n      </p>\n      "
[params.widgets]
categories = true
search = true
tags = true
